<#
.SYNOPSIS
  Regenerates FRENCH_REVIEW.md at the mod root from the shipped Keyed and DefInjected XML, for
  Virginie's French review (TRANSLATIONS.md, "Systematic French review by Virginie").

.DESCRIPTION
  Reads Mod/Languages/English and Mod/Languages/French, keyed by the entry's tag name (Keyed) or
  full relative path (DefInjected), and writes one Markdown table per file: key/path, the source
  text the mod was ported from (this mod has none: it is original, so the "Original" column
  repeats the English text and the file says so once at the top), the English text and the French
  text, verbatim including grammar tokens and any {PAWN_gender ? ...} switch.

  Never edits STATUS.md or claims a review happened: the file is only the material Virginie reads.
#>

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$modLang = Join-Path $root 'Mod/Languages'
$sha = (git -C $root rev-parse --short HEAD 2>$null)
if (-not $sha) { $sha = '(uncommitted)' }

function Get-KeyedEntries([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return @() }
    $doc = [xml](Get-Content -LiteralPath $path -Raw -Encoding UTF8)
    $doc.LanguageData.ChildNodes | Where-Object { $_.NodeType -eq 'Element' } |
        ForEach-Object { [pscustomobject]@{ Key = $_.Name; Text = $_.InnerText } }
}

function New-Table([string]$title, [string]$relPath, [array]$en, [array]$fr) {
    $rows = @()
    $rows += "### $title"
    $rows += ''
    $rows += "Shipped as of ``$sha``, from ``$relPath``."
    $rows += ''
    $rows += '| Key or path | Original | English | French |'
    $rows += '|---|---|---|---|'
    $frByKey = @{}
    foreach ($e in $fr) { $frByKey[$e.Key] = $e.Text }
    foreach ($e in $en) {
        $frText = if ($frByKey.ContainsKey($e.Key)) { $frByKey[$e.Key] } else { '*(missing)*' }
        $escape = { param($s) ($s -replace '\|', '\|') -replace "`n", '<br>' }
        $rows += "| ``$($e.Key)`` | $(& $escape $e.Text) | $(& $escape $e.Text) | $(& $escape $frText) |"
    }
    return ($rows -join "`n")
}

$sections = @()
$sections += "# FRENCH_REVIEW.md"
$sections += ''
$sections += "Generated by ``scripts/Generate-FrenchReview.ps1`` for Virginie's French review"
$sections += "(TRANSLATIONS.md, section 3). Not hand-edited: regenerate instead of correcting a"
$sections += "row here."
$sections += ''
$sections += "**Original:** this mod is original (STATUS.md ``licence: original``), ported from"
$sections += "nothing. The Original column repeats the English text."
$sections += ''

$keyedEn = Get-KeyedEntries (Join-Path $modLang 'English/Keyed/FieldworkCompanions.xml')
$keyedFr = Get-KeyedEntries (Join-Path $modLang 'French/Keyed/FieldworkCompanions.xml')
$sections += New-Table 'Keyed' 'Mod/Languages/English/Keyed/FieldworkCompanions.xml' $keyedEn $keyedFr
$sections += ''

$mbEn = Get-KeyedEntries (Join-Path $modLang 'English/DefInjected/MainButtonDef/FieldworkCompanions.xml')
$mbFr = Get-KeyedEntries (Join-Path $modLang 'French/DefInjected/MainButtonDef/FieldworkCompanions.xml')
if ($mbEn.Count -eq 0 -and $mbFr.Count -gt 0) {
    # English has no DefInjected file: the Def's own label/description are the English source.
    $defDoc = [xml](Get-Content -LiteralPath (Join-Path $root 'Mod/Defs/MainButtonDefs/FieldworkCompanions.xml') -Raw -Encoding UTF8)
    $def = $defDoc.Defs.MainButtonDef
    $mbEn = @(
        [pscustomobject]@{ Key = "$($def.defName).label"; Text = $def.label }
        [pscustomobject]@{ Key = "$($def.defName).description"; Text = $def.description }
    )
}
$sections += New-Table 'DefInjected - MainButtonDef' 'Mod/Languages/French/DefInjected/MainButtonDef/FieldworkCompanions.xml' $mbEn $mbFr
$sections += ''
$sections += '## Notes for the reviewer'
$sections += ''
$sections += '- No text in this mod agrees with a pawn (no `{PAWN_gender ? ...}` switch is used or'
$sections += '  needed): every Keyed entry is a settings label, tooltip or the numeric assist mote'
$sections += '  (`+{0}`), and the sole DefInjected entry is the hidden MainButtons shortcut''s label'
$sections += '  and description. None names a specific colonist or animal. Some speak of the person or animal in general (BondTip, FishingTip, GatheringTip): reworded without gender or the word master after the 2026-10-02 review, so no switch is needed, but the reader should check that none still agrees with a pawn.'
$sections += '- No entry is flagged `?` below: none struck the generating session as uncertain in'
$sections += '  terminology, tone or rewording.'

$outPath = Join-Path $root 'FRENCH_REVIEW.md'
Set-Content -LiteralPath $outPath -Value ($sections -join "`n") -Encoding UTF8
Write-Host "Wrote $outPath ($($keyedEn.Count) Keyed, $($mbFr.Count) DefInjected entries), revision $sha."
